//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLoanDetail
    {
        public int Id { get; set; }
        public int EmployeeLoanId { get; set; }
        public System.DateTime InstallmentMonth { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountPaid { get; set; }
        public bool IsPaid { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual EmployeeLoan EmployeeLoan { get; set; }
    }
}
