//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public int Id { get; set; }
        public string Institute { get; set; }
        public string Major { get; set; }
        public string Level { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public decimal GradeMark { get; set; }
        public bool Formal { get; set; }
        public int EmployeeId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
