//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public int Id { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public int Shift { get; set; }
        public int EmployeeId { get; set; }
        public int Status { get; set; }
        public System.DateTime CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<System.DateTime> BreakOut { get; set; }
        public Nullable<System.DateTime> BreakIn { get; set; }
        public string Remark { get; set; }
        public int BreakMinutes { get; set; }
        public int BreakEarlyMinutes { get; set; }
        public int BreakLateMinutes { get; set; }
        public int CheckEarlyMinutes { get; set; }
        public int CheckLateMinutes { get; set; }
        public int WorkTimeMinutes { get; set; }
        public int OverTimeMinutes { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
