//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeLoan()
        {
            this.EmployeeLoanDetails = new HashSet<EmployeeLoanDetail>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime LoanDate { get; set; }
        public string Remark { get; set; }
        public int SalaryItemId { get; set; }
        public decimal Interest { get; set; }
        public decimal Amount { get; set; }
        public decimal Total { get; set; }
        public decimal InstallmentValue { get; set; }
        public int InstallmentTimes { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PayHead PayHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLoanDetail> EmployeeLoanDetails { get; set; }
    }
}
