//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formula()
        {
            this.SalarySlipDetails = new HashSet<SalarySlipDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SalarySlipDetailId { get; set; }
        public int FirstSalaryItemId { get; set; }
        public string FormulaOp { get; set; }
        public bool IsSecondValue { get; set; }
        public Nullable<int> SecondSalaryItemId { get; set; }
        public decimal SecondValue { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual SalaryItem SalaryItem { get; set; }
        public virtual SalaryItem SalaryItem1 { get; set; }
        public virtual SalarySlipDetail SalarySlipDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalarySlipDetail> SalarySlipDetails { get; set; }
    }
}
