//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPMachine
    {
        public int Id { get; set; }
        public int CompanyInfoId { get; set; }
        public string MachineName { get; set; }
        public int MachineNumber { get; set; }
        public int CommType { get; set; }
        public string EthernetIP { get; set; }
        public int EthernetPort { get; set; }
        public string EthernetMAC { get; set; }
        public string SerialPort { get; set; }
        public int SerialBaudRate { get; set; }
        public string Password { get; set; }
        public string TimeZone { get; set; }
        public decimal TimeZoneOffset { get; set; }
        public string Platform { get; set; }
        public string FirmwareVer { get; set; }
        public string ArithmeticVer { get; set; }
        public string SerialNumber { get; set; }
        public long UserCount { get; set; }
        public long AdminCount { get; set; }
        public long FPCount { get; set; }
        public long FCCount { get; set; }
        public long PasswordCount { get; set; }
        public long AttLogCount { get; set; }
        public bool IsAutoConnect { get; set; }
        public bool IsDisabled { get; set; }
        public bool IsClearLogAfterDownload { get; set; }
        public Nullable<System.DateTime> LastSync { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual CompanyInfo CompanyInfo { get; set; }
    }
}
