//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransaction
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string InventoryGuid { get; set; }
        public string InvoiceNo { get; set; }
        public int SupplierId { get; set; }
        public int WarehouseId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public decimal BalanceQty { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string GoodsType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual InventoryTransaction InventoryTransaction1 { get; set; }
        public virtual InventoryTransaction InventoryTransaction2 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
        public virtual TransactionType TransactionType1 { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
