//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMaster()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int Id { get; set; }
        public string VoucherNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> SuffixPrefixId { get; set; }
        public Nullable<System.DateTime> LedgerDate { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Narration { get; set; }
        public Nullable<int> VoucherTypeId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<System.DateTime> ExtraDate { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedNotes { get; set; }
        public Nullable<System.DateTime> ApprovedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
