//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PensionCompensation
    {
        public int Id { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string UserName { get; set; }
        public System.DateTime PensionDate { get; set; }
        public int EmployeeId { get; set; }
        public decimal PensionValue { get; set; }
        public decimal PensionMultiply { get; set; }
        public decimal MedAndHousing { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
