//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryProcess
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Name { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> Attendance { get; set; }
        public Nullable<int> Leave { get; set; }
        public Nullable<int> Absent { get; set; }
        public Nullable<decimal> Addition { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> SalaryYear { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
    }
}
