//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySlipDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalarySlipDetail()
        {
            this.Formulae = new HashSet<Formula>();
        }
    
        public int Id { get; set; }
        public int Index { get; set; }
        public int SalarySign { get; set; }
        public int SalarySlipId { get; set; }
        public int FormulaId { get; set; }
        public decimal Value { get; set; }
        public bool HasMinValue { get; set; }
        public decimal MinValue { get; set; }
        public bool HasMaxValue { get; set; }
        public decimal MaxValue { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formula> Formulae { get; set; }
        public virtual Formula Formula { get; set; }
        public virtual SalarySlip SalarySlip { get; set; }
    }
}
