//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlipGajiDetail1
    {
        public int Id { get; set; }
        public int SlipGajiDetailId { get; set; }
        public string NoBadge { get; set; }
        public System.DateTime Tanggal { get; set; }
        public string Shift { get; set; }
        public string Status { get; set; }
        public decimal jamkerjaActual { get; set; }
        public decimal jamReg { get; set; }
        public decimal Lembur15 { get; set; }
        public decimal Lembur20 { get; set; }
        public decimal Lembur30 { get; set; }
        public decimal Lembur40 { get; set; }
        public string nmhari { get; set; }
    
        public virtual SlipGajiDetail SlipGajiDetail { get; set; }
    }
}
