//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlipGajiDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlipGajiDetail()
        {
            this.SlipGajiDetail1 = new HashSet<SlipGajiDetail1>();
            this.SlipGajiDetail2A = new HashSet<SlipGajiDetail2A>();
            this.SlipGajiDetail2A1 = new HashSet<SlipGajiDetail2A>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime MONTH { get; set; }
        public string NoBadge { get; set; }
        public string Name { get; set; }
        public string Jabatan { get; set; }
        public System.DateTime TanggalPenerimaan { get; set; }
        public System.DateTime PeriodeAwal { get; set; }
        public System.DateTime PeriodeAkhir { get; set; }
        public decimal GajiBasis { get; set; }
        public string StatusMarriage { get; set; }
        public decimal NoSlip { get; set; }
        public decimal Rate { get; set; }
        public decimal Lembur15 { get; set; }
        public decimal Lembur20 { get; set; }
        public decimal Lembur30 { get; set; }
        public decimal Lembur40 { get; set; }
        public string Disiapkan_oleh { get; set; }
        public string Disetujui_oleh { get; set; }
        public string Dikoreksi_oleh { get; set; }
        public string company_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlipGajiDetail1> SlipGajiDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlipGajiDetail2A> SlipGajiDetail2A { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlipGajiDetail2A> SlipGajiDetail2A1 { get; set; }
    }
}
