//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkingTime()
        {
            this.EmployeeWorkingTimes = new HashSet<EmployeeWorkingTime>();
            this.WorkingDays = new HashSet<WorkingDay>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public System.DateTime MinCheckIn { get; set; }
        public System.DateTime MaxCheckIn { get; set; }
        public System.DateTime MinCheckOut { get; set; }
        public System.DateTime MaxCheckOut { get; set; }
        public System.DateTime BreakIn { get; set; }
        public System.DateTime BreakOut { get; set; }
        public decimal CheckInTolerance { get; set; }
        public decimal CheckOutTolerance { get; set; }
        public decimal WorkInterval { get; set; }
        public decimal BreakInterval { get; set; }
        public string TimeZone { get; set; }
        public decimal TimeZoneOffset { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeWorkingTime> EmployeeWorkingTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingDay> WorkingDays { get; set; }
    }
}
