//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexERP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingDay
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public System.DateTime MinCheckIn { get; set; }
        public System.DateTime MaxCheckIn { get; set; }
        public System.DateTime MinCheckOut { get; set; }
        public System.DateTime MaxCheckOut { get; set; }
        public System.DateTime BreakIn { get; set; }
        public System.DateTime BreakOut { get; set; }
        public decimal CheckInTolerance { get; set; }
        public decimal CheckOutTolerance { get; set; }
        public decimal WorkInterval { get; set; }
        public decimal BreakInterval { get; set; }
        public Nullable<int> WorkingTimeId { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsShortestDay { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual WorkingTime WorkingTime { get; set; }
    }
}
